# -*- coding: utf-8 -*-
"""Task09-optional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EhMtP_gVI5dx7l1kyR5fB_s12Z0_9aGM

**Task 09: Data linking**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Spanish: Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos.

English: Search for individuals in both graphs and link them using the OWL:sameAs property; insert these matches into g3. We consider two individuals to be the same if they have the same first name and surname. Please note that the URIs do not necessarily have to be the same for the same individual in both graphs.
"""

RDF = Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
OWL = Namespace("http://www.w3.org/2002/07/owl#")
ns3 = Namespace("http://data.three.org#")
ns4 = Namespace("http://data.four.org#")

for person1 in g1.subjects(RDF.type, ns3.Person):
  given1 = g1.value(person1, vcard.Given, None)
  family1 = g1.value(person1, vcard.Family, None)

  for person2 in g2.subjects(RDF.type, ns4.Person):
    given2 = g2.value(person2, vcard.Given, None)
    family2 = g2.value(person2, vcard.Family, None)

    if given1 is not None and family1 is not None:
      if given1 == given2 and family1 == family2:
        g3.add((person1, OWL.sameAs, person2))

print(g3.serialize(format="ttl"))