# -*- coding: utf-8 -*-
"""Task08-optional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10CGllc3nQMxc8AcyNW1uFXUt4HHa96m0

**Task 08: Completing missing data**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Spanish: Lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas.

English: List all the elements of the Person class in the first graph (data01.rdf) and fill in any missing fields (given name, family name and email) using the data from the second graph (data02.rdf). You can use SPARQL queries or iterate through the graph, or both.
"""

RDF = Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
ns = Namespace("http://data.org#")

for person in g1.subjects(RDF.type, ns.Person):
  given = g1.value(person, vcard.Given, None)
  family = g1.value(person, vcard.Family, None)
  email = g1.value(person, vcard.EMAIL, None)

  if given is None:
    given = g2.value(person, vcard.Given, None)

  if family is None:
    family = g2.value(person, vcard.Family, None)

  if email is None:
    email = g2.value(person, vcard.EMAIL, None)

  print(f"{person}; Given name: {given}; Familiy name: {family}; Email: {email}")