# -*- coding: utf-8 -*-
"""Task08-optional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/FacultadInformatica-LinkedData/Curso2026-2027-ODKG/blob/master/Assignment4/course_materials/notebooks/Task08-optional.ipynb

**Task 08: Completing missing data**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import RDF, RDFS, FOAF
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Spanish: Lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas.

English: List all the elements of the Person class in the first graph (data01.rdf) and fill in any missing fields (given name, family name and email) using the data from the second graph (data02.rdf). You can use SPARQL queries or iterate through the graph, or both.
"""

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
FOAF_NS = Namespace("http://xmlns.com/foaf/0.1/")

#Compatible predicates (as errors have emerged from this)
given_predicates = [
    VCARD.Given,
    FOAF.givenName,
    FOAF_NS.givenname,
    URIRef("http://xmlns.com/foaf/0.1/givenname")
]

family_predicates = [
    VCARD.Family,
    FOAF.familyName,
    FOAF_NS.family_name,
    URIRef("http://xmlns.com/foaf/0.1/family_name")
]

email_predicates = [
    VCARD.EMAIL,
    FOAF_NS.email,
    FOAF.mbox,
    URIRef("http://xmlns.com/foaf/0.1/email")
]

#Identify all people in g1
person_classes = [
    FOAF.Person,
    URIRef("http://data.org#Person"),
    URIRef("http://somewhere#Person"),
    URIRef("http://oeg.fi.upm.es/def/people#Person")
]

people_g1 = set()
for pc in person_classes:
    for s in g1.subjects(RDF.type, pc):
        people_g1.add(s)

#If not found directly, I need to add this step
if not people_g1:
    for s, p, o in g1.triples((None, RDF.type, None)):
        if "Person" in str(o):
            people_g1.add(s)

property_groups = [
    ("given_name", given_predicates),
    ("family_name", family_predicates),
    ("email", email_predicates)
]

#If missing information for people in g1, complete it with g2
for person in people_g1:
    for field_name, pred_list in property_groups:
        # Comprobar si ya existe algún valor en g1 para ese campo
        has_field_g1 = any(list(g1.objects(person, pred)) for pred in pred_list)

        if not has_field_g1:
            # Buscar el valor en g2 usando cualquiera de los predicados compatibles
            for pred in pred_list:
                for obj in g2.objects(person, pred):
                    g1.add((person, pred, obj))

#Visualize the result
for person in people_g1:
    print(f"\nRecurso: {person}")
    for p, o in g1.predicate_objects(person):
        print(f"  {p} -> {o}")