# -*- coding: utf-8 -*-
"""Task09-optional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/FacultadInformatica-LinkedData/Curso2026-2027-ODKG/blob/master/Assignment4/course_materials/notebooks/Task09-optional.ipynb

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import RDF, OWL

g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Spanish: Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos.

English: Search for individuals in both graphs and link them using the OWL:sameAs property; insert these matches into g3. We consider two individuals to be the same if they have the same first name and surname. Please note that the URIs do not necessarily have to be the same for the same individual in both graphs.
"""

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
FOAF_NS = Namespace("http://xmlns.com/foaf/0.1/")

#Predicates which can store given and family name
given_predicates = [
    VCARD.Given,
    FOAF_NS.givenName,
    FOAF_NS.givenname,
    URIRef("http://xmlns.com/foaf/0.1/givenname")
]

family_predicates = [
    VCARD.Family,
    FOAF_NS.familyName,
    FOAF_NS.family_name,
    URIRef("http://xmlns.com/foaf/0.1/family_name")
]

def get_name_parts(graph, individual):
    given, family = None, None
    for p in given_predicates:
        val = graph.value(individual, p)
        if val is not None:
            given = str(val).strip().lower()
            break

    for p in family_predicates:
        val = graph.value(individual, p)
        if val is not None:
            family = str(val).strip().lower()
            break

    return given, family

#Obtain g1 entities (with name and surname)
entities_g1 = {}
for s in set(g1.subjects()):
    g_name, f_name = get_name_parts(g1, s)
    if g_name and f_name:
        entities_g1[(g_name, f_name)] = s

#Compare with g2 entities and add them in g3
for s in set(g2.subjects()):
    g_name, f_name = get_name_parts(g2, s)
    if g_name and f_name:
        key = (g_name, f_name)
        if key in entities_g1:
            ind1 = entities_g1[key]
            ind2 = s
            g3.add((ind1, OWL.sameAs, ind2))

#Visualize g3
for s, p, o in g3:
    print(f"{s} owl:sameAs {o}")