# -*- coding: utf-8 -*-
"""bbarahon-Task08-optional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mTcLyL_u8RDqJZgx7pZ4jVv6cgbGDtM7

**Task 08: Completing missing data**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Spanish: Lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas.

English: List all the elements of the Person class in the first graph (data01.rdf) and fill in any missing fields (given name, family name and email) using the data from the second graph (data02.rdf). You can use SPARQL queries or iterate through the graph, or both.
"""

query = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX data: <http://data.org#>
PREFIX v1: <http://www.w3.org/2001/vcard-rdf/3.0#>
PREFIX v2: <http://www.w3.org/2001/vcard-rdf/3.0/>

SELECT ?person ?given ?family ?email
WHERE {
    ?person rdf:type data:Person .

    OPTIONAL {
        ?person v1:Given ?given1 .
    }

    OPTIONAL {
        ?person v1:Family ?family1 .
    }

    OPTIONAL {
        ?person v1:EMAIL ?email1 .
    }

    OPTIONAL {
        ?person v2:Given ?given2 .
    }

    OPTIONAL {
        ?person v2:Family ?family2 .
    }

    OPTIONAL {
        ?person v2:EMAIL ?email2 .
    }

    BIND(COALESCE(?given1, ?given2) AS ?given)
    BIND(COALESCE(?family1, ?family2) AS ?family)
    BIND(COALESCE(?email1, ?email2) AS ?email)
}
"""
 #Lo distinto va a ser cómo indexo en los enlaces, por eso existe un v1 y un v2 de vcard
g = Graph()
for triple in g1:
    g.add(triple)
for triple in g2:
    g.add(triple)
results = list(g.query(query))

print("Número de personas:", len(results))

for row in results:
    print("Person:", row.person)
    print("Given:", row.given)
    print("Family:", row.family)
    print("Email:", row.email)
    print("------------------")

