# -*- coding: utf-8 -*-
"""bbarahon-Task09-optional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vdcu9dCTOVXpprzxHnP01aL2ymcVqCfJ

**Task 09: Data linking**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Spanish: Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos.

English: Search for individuals in both graphs and link them using the OWL:sameAs property; insert these matches into g3. We consider two individuals to be the same if they have the same first name and surname. Please note that the URIs do not necessarily have to be the same for the same individual in both graphs.
"""

g3 = Graph()
# Namespaces
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
OWL = Namespace("http://www.w3.org/2002/07/owl#")
# (nickname, familyName) -> URI
for ind1 in g1.subjects():
    nombre1 = g1.value(ind1, VCARD.Given)
    apellido1 = g1.value(ind1, VCARD.Family)
    # Solo personas con nombre y apellido
    if nombre1 is None or apellido1 is None:
        continue
    for ind2 in g2.subjects():
        nombre2 = g2.value(ind2, VCARD.Given)
        apellido2 = g2.value(ind2, VCARD.Family)
        if nombre2 is None or apellido2 is None:
            continue
        if nombre1 == nombre2 and apellido1 == apellido2:
            g3.add((ind1, OWL.sameAs, ind2))
print("\n Número de triples en g3:", len(g3))
print("\n Triples en grafo 3:")
for triple in g3:
    print(triple)

