# -*- coding: utf-8 -*-
"""Task09-optional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/FacultadInformatica-LinkedData/Curso2026-2027-ODKG/blob/master/Assignment4/course_materials/notebooks/Task09-optional.ipynb

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Spanish: Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos.

English: Search for individuals in both graphs and link them using the OWL:sameAs property; insert these matches into g3. We consider two individuals to be the same if they have the same first name and surname. Please note that the URIs do not necessarily have to be the same for the same individual in both graphs.
"""

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

def get_persons(g):
    persons = {}
    for s in set(g.subjects()):
        given = g.value(s, VCARD.Given)
        family = g.value(s, VCARD.Family)
        if given is not None and family is not None:
            persons[s] = (str(given), str(family))
    return persons

persons_g1 = get_persons(g1)
persons_g2 = get_persons(g2)

for uri1, (given1, family1) in persons_g1.items():
    for uri2, (given2, family2) in persons_g2.items():
        if given1 == given2 and family1 == family2:
            g3.add((uri1, OWL.sameAs, uri2))

for s, p, o in g3:
    print(s, p, o)